version: 2
jobs:
  build:
    docker:
      - image: tigefa/bionic-desktop
    steps:
      - checkout
      
      - setup_remote_docker
      
      - run:
          name: Install Docker client
          command: |
            wget -qO- https://get.docker.com/ | sh
           
      - run:
          name: Install and Update Packages
          command: |
            apt update -yqq
            apt upgrade -yqq
            apt install -yqq sudo curl wget netcat whois figlet apt-utils software-properties-common
            sudo add-apt-repository ppa:certbot/certbot -y
            sudo apt-get update
            sudo apt-get dist-upgrade -yqq
            sudo apt-get install -yqq python-certbot-apache
            
      - run:
          name: Print the Current Time
          command: date
